Repository googleapis/java-document-ai, pull requests merged in 2020-08, with the labels that each got.

#142 chore(docs): add cloud-RAD
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: automerge, context: full

#143 chore: regenerate common templates
  .kokoro/continuous/dependencies.cfg
  .kokoro/continuous/integration.cfg
  .kokoro/continuous/java11.cfg
  .kokoro/continuous/java7.cfg
  .kokoro/continuous/java8-osx.cfg
  .kokoro/continuous/java8-win.cfg
  .kokoro/continuous/lint.cfg
  .kokoro/continuous/propose_release.cfg
  .kokoro/continuous/samples.cfg
  .kokoro/dependencies.sh
  .kokoro/nightly/dependencies.cfg
  .kokoro/nightly/lint.cfg
  synth.metadata
Labels: automerge, context: full

#149 chore: regenerate README
  README.md
  synth.metadata
Labels: context: none

#153 Fixed POM file links to match true Github links
  google-cloud-document-ai-bom/pom.xml
  google-cloud-document-ai/pom.xml
  pom.xml
Labels: automerge

#156 samples: add presubmit lint check
  .github/workflows/samples.yaml
  README.md
  samples/snippets/src/main/java/documentai/v1beta2/ParseWithModelBeta.java
  synth.metadata
Labels: api: documentai, automerge, context: partial
