Repository googleapis/java-document-ai, pull requests merged in 2020-11, with the labels that each got.

#239 test: re-enable BatchParseTable test
  samples/snippets/src/main/java/documentai/v1beta2/BatchParseTableBeta.java
  samples/snippets/src/test/java/documentai/v1beta2/BatchParseTableBetaTest.java
Labels: api: documentai, automerge, cla: yes

#258 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: documentai, automerge, cla: yes

#260 chore(java): use production staging bucket
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: api: documentai, automerge, cla: yes, context: full

#259 chore: Fix namespaces for Ruby, PHP, and C# clients
  proto-google-cloud-document-ai-v1beta1/src/main/java/com/google/cloud/documentai/v1beta1/DocumentAiProto.java
  proto-google-cloud-document-ai-v1beta1/src/main/java/com/google/cloud/documentai/v1beta1/DocumentProto.java
  proto-google-cloud-document-ai-v1beta1/src/main/java/com/google/cloud/documentai/v1beta1/GeometryProto.java
  proto-google-cloud-document-ai-v1beta1/src/main/proto/google/cloud/documentai/v1beta1/document.proto
  proto-google-cloud-document-ai-v1beta1/src/main/proto/google/cloud/documentai/v1beta1/document_understanding.proto
  proto-google-cloud-document-ai-v1beta1/src/main/proto/google/cloud/documentai/v1beta1/geometry.proto
  proto-google-cloud-document-ai-v1beta2/src/main/java/com/google/cloud/documentai/v1beta2/DocumentAiProto.java
  proto-google-cloud-document-ai-v1beta2/src/main/java/com/google/cloud/documentai/v1beta2/DocumentProto.java
  proto-google-cloud-document-ai-v1beta2/src/main/java/com/google/cloud/documentai/v1beta2/GeometryProto.java
  proto-google-cloud-document-ai-v1beta2/src/main/proto/google/cloud/documentai/v1beta2/document.proto
  proto-google-cloud-document-ai-v1beta2/src/main/proto/google/cloud/documentai/v1beta2/document_understanding.proto
  proto-google-cloud-document-ai-v1beta2/src/main/proto/google/cloud/documentai/v1beta2/geometry.proto
  proto-google-cloud-document-ai-v1beta3/src/main/java/com/google/cloud/documentai/v1beta3/DocumentAiProcessorService.java
  proto-google-cloud-document-ai-v1beta3/src/main/java/com/google/cloud/documentai/v1beta3/DocumentProto.java
  proto-google-cloud-document-ai-v1beta3/src/main/java/com/google/cloud/documentai/v1beta3/GeometryProto.java
  proto-google-cloud-document-ai-v1beta3/src/main/proto/google/cloud/documentai/v1beta3/document.proto
  proto-google-cloud-document-ai-v1beta3/src/main/proto/google/cloud/documentai/v1beta3/document_processor_service.proto
  proto-google-cloud-document-ai-v1beta3/src/main/proto/google/cloud/documentai/v1beta3/geometry.proto
  synth.metadata
Labels: api: documentai, cla: yes, context: full

#262 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: documentai, automerge, cla: yes

#263 chore(java): ignore return code 28 in README autosynth job
  .kokoro/readme.sh
  synth.metadata
Labels: api: documentai, automerge, cla: yes, context: full

#269 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: documentai, automerge, cla: yes

#272 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: documentai, automerge, cla: yes

#271 build(java): use code-suggester v1 tag rather than full semver
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: documentai, automerge, cla: yes, context: full

#276 build(java): use actions/github-script v3 tag rather than full semver
  .github/workflows/approve-readme.yaml
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: documentai, automerge, cla: yes, context: full

#278 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: documentai, automerge, cla: yes

#279 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: documentai, automerge, cla: yes

#280 chore(java): retry staging portion of the release with backoff
  .kokoro/common.sh
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: documentai, automerge, cla: yes, context: full

#281 build(java): enable blunderbuss for samples
  .github/blunderbuss.yml
  synth.metadata
Labels: api: documentai, automerge, cla: yes, context: full, samples
