Repository googleapis/java-document-ai, pull requests merged in 2020-09, with the labels that each got.

#160 build: fix release reporting
  .kokoro/release/stage.cfg
  synth.metadata
Labels: api: documentai, context: full

#171 build(ci): enable auto-release for dependency-update-only releases
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: documentai, cla: yes, context: full

#172 chore(java): set yoshi-java as default CODEOWNER
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, cla: yes, context: full

#185 chore: regenerate README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#187 build(java): use yoshi-approver token for auto-approve
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#188 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: api: documentai, automerge, cla: yes

#195 chore: regenerate templates
  .github/readme/synth.py
  .github/workflows/auto-release.yaml
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#197 build: rename samples lint workflow to checkstyle to disambiguate branch protection with unit lint
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
