Repository googleapis/java-document-ai, pull requests merged in 2021-05, with the labels that each got.

#462 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: documentai, automerge, cla: yes, context: none

#463 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: documentai, automerge, cla: yes

#464 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: documentai, automerge, cla: yes, context: full

#471 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: documentai, automerge, cla: yes

#477 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: documentai, automerge, cla: yes

#481 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: documentai, automerge, cla: yes, context: full

#482 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: documentai, automerge, cla: yes

#483 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: documentai, automerge, cla: yes

#476 feat: Use non-regionalized default host name for documentai.googleapis.com
  google-cloud-document-ai/src/main/java/com/google/cloud/documentai/v1/DocumentProcessorServiceSettings.java
  google-cloud-document-ai/src/main/java/com/google/cloud/documentai/v1/stub/DocumentProcessorServiceStubSettings.java
  google-cloud-document-ai/src/main/java/com/google/cloud/documentai/v1beta3/DocumentProcessorServiceSettings.java
  google-cloud-document-ai/src/main/java/com/google/cloud/documentai/v1beta3/stub/DocumentProcessorServiceStubSettings.java
  proto-google-cloud-document-ai-v1/src/main/java/com/google/cloud/documentai/v1/DocumentAiProcessorService.java
  proto-google-cloud-document-ai-v1/src/main/proto/google/cloud/documentai/v1/document_processor_service.proto
  proto-google-cloud-document-ai-v1beta3/src/main/java/com/google/cloud/documentai/v1beta3/DocumentAiProcessorService.java
  proto-google-cloud-document-ai-v1beta3/src/main/proto/google/cloud/documentai/v1beta3/document_processor_service.proto
  synth.metadata
Labels: api: documentai, automerge, cla: yes, context: full

#486 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: documentai, automerge, cla: yes

#475 feat: release 1.0.0
  .repo-metadata.json
Labels: api: documentai, cla: yes

#487 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: documentai, automerge, cla: yes

#488 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: documentai, automerge, cla: yes, context: full

#493 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: api: documentai, automerge, cla: yes, context: full

#497 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: documentai, automerge, cla: yes
