Repository googleapis/java-document-ai, pull requests merged in 2021-02, with the labels that each got.

#332 chore: Re-generated to pick up changes from synthtool.
  .github/workflows/ci.yaml
  .kokoro/linkage-monitor.sh
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: documentai, cla: yes

#334 build(java): update autorelease branch name check
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: documentai, automerge, cla: yes, context: full

#335 chore: Re-generated to pick up changes from synthtool.
  .kokoro/release/publish_javadoc11.cfg
  LICENSE
  synth.metadata
Labels: automerge, cla: yes, context: full

#338 docs: generate sample code in the Java microgenerator
  google-cloud-document-ai/src/main/java/com/google/cloud/documentai/v1beta1/DocumentUnderstandingServiceClient.java
  google-cloud-document-ai/src/main/java/com/google/cloud/documentai/v1beta1/package-info.java
  google-cloud-document-ai/src/main/java/com/google/cloud/documentai/v1beta2/DocumentUnderstandingServiceClient.java
  google-cloud-document-ai/src/main/java/com/google/cloud/documentai/v1beta2/package-info.java
  google-cloud-document-ai/src/main/java/com/google/cloud/documentai/v1beta3/DocumentProcessorServiceClient.java
  google-cloud-document-ai/src/main/java/com/google/cloud/documentai/v1beta3/package-info.java
  synth.metadata
Labels: api: documentai, automerge, cla: yes, context: full, samples

#340 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: documentai, automerge, cla: yes

#345 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: documentai, automerge, cla: yes

#344 build(java): update autorelease script
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: documentai, automerge, cla: yes, context: full

#343 chore: added conditonal check to prevent indexOutOfBound Exception
  samples/snippets/src/main/java/documentai/v1beta2/BatchParseFormBeta.java
  samples/snippets/src/main/java/documentai/v1beta2/BatchParseTableBeta.java
  samples/snippets/src/main/java/documentai/v1beta2/ParseFormBeta.java
  samples/snippets/src/main/java/documentai/v1beta2/ParseTableBeta.java
Labels: api: documentai, cla: yes

#348 ci: linkage monitor CI job to use build.sh
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: documentai, automerge, cla: yes, context: full

#347 chore: update gapic-generator-java to 0.0.20
  google-cloud-document-ai/src/main/java/com/google/cloud/documentai/v1beta1/stub/GrpcDocumentUnderstandingServiceStub.java
  google-cloud-document-ai/src/main/java/com/google/cloud/documentai/v1beta2/stub/GrpcDocumentUnderstandingServiceStub.java
  google-cloud-document-ai/src/main/java/com/google/cloud/documentai/v1beta3/stub/GrpcDocumentProcessorServiceStub.java
  google-cloud-document-ai/src/test/java/com/google/cloud/documentai/v1beta1/MockDocumentUnderstandingServiceImpl.java
  google-cloud-document-ai/src/test/java/com/google/cloud/documentai/v1beta2/MockDocumentUnderstandingServiceImpl.java
  google-cloud-document-ai/src/test/java/com/google/cloud/documentai/v1beta3/MockDocumentProcessorServiceImpl.java
  synth.metadata
Labels: api: documentai, automerge, cla: yes, context: full

#352 build: skip Maven download logs
  .kokoro/build.sh
  synth.metadata
Labels: api: documentai, automerge, cla: yes, context: full

#353 build: reduce download junk in log files
  .kokoro/build.sh
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: documentai, automerge, cla: yes, context: full

#355 chore: release gapic-generator-java v0.0.21 with gapic_metadata.json support
  google-cloud-document-ai/src/main/java/com/google/cloud/documentai/v1beta1/gapic_metadata.json
  google-cloud-document-ai/src/main/java/com/google/cloud/documentai/v1beta2/gapic_metadata.json
  google-cloud-document-ai/src/main/java/com/google/cloud/documentai/v1beta3/gapic_metadata.json
  synth.metadata
Labels: api: documentai, automerge, cla: yes, context: full

#360 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: documentai, automerge, cla: yes

#361 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: documentai, automerge, cla: yes

#363 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: documentai, automerge, cla: yes
