Repository googleapis/java-document-ai, pull requests merged in 2021-04, with the labels that each got.

#402 chore: increased timeout len
  samples/snippets/src/main/java/documentai/v1beta3/BatchProcessDocumentBeta.java
Labels: api: documentai, cla: yes

#408 build(java): skip javadoc tests during dependencies test
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: documentai, automerge, cla: yes, context: full

#409 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: documentai, automerge, cla: yes

#411 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: documentai, automerge, cla: yes

#414 fix: typo
  .kokoro/build.sh
  synth.metadata
Labels: api: documentai, automerge, cla: yes, context: full

#418 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: documentai, automerge, cla: yes

#419 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: documentai, automerge, cla: yes

#422 chore: start tracking obsolete files
  synth.metadata
Labels: api: documentai, automerge, cla: yes, context: full

#424 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: documentai, automerge, cla: yes

#426 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: documentai, automerge, cla: yes

#428 chore: add ml-apis as samples CODEOWNERS
  .github/CODEOWNERS
Labels: api: documentai, automerge, cla: yes, samples

#430 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: documentai, automerge, cla: yes

#431 chore: Re-generated to pick up changes from self
  .github/CODEOWNERS
  synth.metadata
Labels: api: documentai, cla: yes, context: none

#435 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: documentai, automerge, cla: yes

#437 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: documentai, automerge, cla: yes

#446 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: documentai, automerge, cla: yes

#450 feat: add confidence field to the PageAnchor.PageRef in document.proto
  proto-google-cloud-document-ai-v1beta3/src/main/java/com/google/cloud/documentai/v1beta3/Document.java
  proto-google-cloud-document-ai-v1beta3/src/main/java/com/google/cloud/documentai/v1beta3/DocumentProto.java
  proto-google-cloud-document-ai-v1beta3/src/main/proto/google/cloud/documentai/v1beta3/document.proto
  synth.metadata
Labels: api: documentai, automerge, cla: yes, context: full

#453 feat: add confidence field to the PageAnchor.PageRef in document.proto
  proto-google-cloud-document-ai-v1/src/main/java/com/google/cloud/documentai/v1/Document.java
  proto-google-cloud-document-ai-v1/src/main/java/com/google/cloud/documentai/v1/DocumentProto.java
  proto-google-cloud-document-ai-v1/src/main/proto/google/cloud/documentai/v1/document.proto
  synth.metadata
Labels: api: documentai, automerge, cla: yes, context: full

#459 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: documentai, automerge, cla: yes

#460 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: documentai, automerge, cla: yes
